DatabaseSettings:
  DatabaseURI: "root:123456@tcp(127.0.0.1:3306)/tiktok?parseTime=True&loc=Local"
  DatabaseName: "tiktok"
  Username: "root"
  Password: "123456"

JWTSettings:
  SecretKey: "wokanguoliuxingzhuiruodimian"


QiniuSettings:
  AccessKey: AEj6dhT5C0vmu4_Rx5jQrpeOrGhx9sDBKEl8p5Uh
  SecretKey: fUslXvpVI-yF9VnZdkBvyFlvEvfOROVS4TrsBJQt
  Bucket: my-tiktok
  Prefix: http://tiktok.tudoutiao.pro/
  VideoPath: video/

RedisSettings:
  Host: 43.143.224.79
  Port: 6379
  PassWord: 123456
  DB: 0
